version: "3.8"

services:
  mymongodb:
    image: "mongo"

    ports:
      - "27017:27017"

    volumes:
      - data:/data/db

  backend:
    build: ./node
    ports:
      - "8080:8080"

    depends_on:
      - mymongodb

  frontend:
    build: ./front

    ports:
      - "3000:3000"
    volumes:
      - ./front/src:/app/src
    stdin_open: true
    tty: true

    depends_on:
      - backend

volumes:
  data: